using RealWare.Core.ExternalApproach.Models.Request;

namespace RealWare.Core.Tests.ExternalApproach
{
    [TestClass]
    public class ExternalApproachModelTests
    {
        [TestMethod]
        public void Deserialize_ExternalApproachProperty_FromJson()
        {
            var result = Newtonsoft.Json.JsonConvert.DeserializeObject<ExternalApproachProperty>(testPropertyJson);

            Assert.IsNotNull(result, "Conversion failed.");
        }



        private string testPropertyJson = @"
        {
            ""AccountNo"": ""R87055730355320"",
            ""ImpNo"": 1.00,
            ""ImpDescription"": """",
            ""CostValueBy"": ""SF"",
            ""MarketValueBy"": ""SF"",
            ""IncomeValueBy"": ""SF"",
            ""LandAttributedPct"": 1.0000,
            ""ImpCompletedPct"": 1.0000,
            ""ImpQuality"": ""Average"",
            ""ImpUnitType"": """",
            ""ImpDesignAdjPct"": 0.0000,
            ""ImpExteriorAdjPct"": 0.0000,
            ""ImpPhysicalDeprPct"": 0.0000,
            ""FunctionalObsolescePct"": 0.0000,
            ""EconomicObsolescePct"": 0.0000,
            ""ImpOtherAdjPct"": 0.0000,
            ""MHTitleNo"": """",
            ""MHSerialNo"": ""R87055730355320"",
            ""MHTotalLength"": null,
            ""MHDecalNo"": """",
            ""MHTagNo"": """",
            ""Appraiser"": ""431"",
            ""AppraisalDate"": ""2024-09-13T00:00:00"",
            ""OwnerOccupiedFlag"": 0,
            ""CostMethod"": ""RCNLD"",
            ""MarketMethod"": ""External Market Value"",
            ""IncomeMethod"": """",
            ""ImpConditionType"": ""Avg"",
            ""CondoLandPercent"": 0.000000,
            ""Impsf"": 2221,
            ""CondoImpPercent"": 0.000000,
            ""ImpPerimeter"": 220,
            ""ImPInteriorAdjPct"": 0.0000,
            ""CondoImpsf"": 0,
            ""ImpAmateurAdjPct"": 0.0000,
            ""ImpNetSf"": 0,
            ""PropertyType"": ""Residential"",
            ""ApproAchType"": ""Market"",
            ""Impsot0"": """",
            ""Impsot1"": """",
            ""Impsom0"": """",
            ""Impsom1"": """",
            ""Impsod0"": null,
            ""Impsod1"": null,
            ""Impson0"": null,
            ""Impson1"": null,
            ""Impson2"": null,
            ""WriteDate"": ""2025-01-10T21:37:25"",
            ""SeqId"": 254917896,
            ""Occupancies"": [
                {
                    ""DetailId"": 100083413038,
                    ""AccountNo"": ""R87055730355320"",
                    ""ImpNo"": 1.00,
                    ""OccCode"": 100,
                    ""OccPercent"": 1.0000,
                    ""AbstractCode"": ""100"",
                    ""ImpAbstractValue"": 0.00,
                    ""AbstractInDate"": null,
                    ""AbstractOutDate"": null,
                    ""AbstractAdjCode"": """",
                    ""ProrateType"": """",
                    ""TaxDistrict"": ""T-4A"",
                    ""ImpsOccot0"": """",
                    ""ImpsOccot1"": """",
                    ""ImpsOcCom0"": """",
                    ""ImpsOcCom1"": """",
                    ""ImpsOccod0"": null,
                    ""ImpsOccod1"": null,
                    ""ImpsOccon0"": 0.0,
                    ""ImpsOccon1"": 0.0,
                    ""ImpsOccon2"": 0.0,
                    ""WriteDate"": ""2025-01-10T21:37:25"",
                    ""OccCompletedPct"": 1.0000,
                    ""SeqId"": 255067916,
                    ""RoomCountOverride"": null,
                    ""BltAsUnitCountOverride"": null,
                    ""ImpsfOverride"": null,
                    ""ImpBltAsOtherOverride"": null,
                    ""MarketValueOverrideFlag"": 0
                }
            ],
            ""BuiltAs"": [
                {
                    ""DetailId"": 100083413037,
                    ""AccountNo"": ""R87055730355320"",
                    ""ImpNo"": 1.00,
                    ""BltAsCode"": 1,
                    ""HvacPercent"": 1.0000,
                    ""CLimate"": ""Moderate"",
                    ""ImpExterior"": ""Frame Brick/Stone Veneer"",
                    ""ImPInterior"": ""Drywall"",
                    ""BltAsstories"": 1.00,
                    ""BltAsStoryHeight"": 8,
                    ""RoofType"": ""Gable/Hip"",
                    ""RoofCover"": ""Composition Shingle"",
                    ""FloorCover"": ""Allowance"",
                    ""BltAsFoundation"": ""Slab"",
                    ""RoomCount"": null,
                    ""BedroomCount"": 0.0,
                    ""BltAsTotalUnitCount"": 0,
                    ""ImpBltAsOther"": 0,
                    ""ClassCode"": """",
                    ""Diameter"": null,
                    ""Capacity"": null,
                    ""BltAsHorsepower"": null,
                    ""BltAsHeight"": 0,
                    ""BltAsYearBuilt"": 2020,
                    ""YearreModeled"": null,
                    ""ReModeledPercent"": 0.0000,
                    ""EffectiveAge"": null,
                    ""BltAsLength"": 0,
                    ""BltAsWidth"": 0,
                    ""MHTagLength"": 0,
                    ""MHTagWidth"": 0,
                    ""MHSkirt"": """",
                    ""MHSkirtLinearFeet"": 0,
                    ""MHWallType"": ""2X4"",
                    ""BltAsSf"": 2221,
                    ""SprinklerSf"": 0,
                    ""BathCount"": 2.10,
                    ""PrimaryBltAsOrderNo"": null,
                    ""HvacType"": ""Cool Air in Heat Ducts"",
                    ""ImpsBltAsot0"": """",
                    ""ImpsBltAsot1"": """",
                    ""ImpsBltAsom0"": """",
                    ""ImpsBltAsom1"": """",
                    ""ImpsBltAsod0"": null,
                    ""ImpsBltAsod1"": null,
                    ""ImpsBltAson0"": 0.0,
                    ""ImpsBltAson1"": 0.0,
                    ""ImpsBltAson2"": 0.0,
                    ""WriteDate"": ""2024-09-13T10:20:25"",
                    ""MHDeprCode"": """",
                    ""MHmake"": """",
                    ""MHModelName"": """",
                    ""SeqId"": 253823496,
                    ""APexId"": null,
                    ""ExternalCostValue"": 0.0,
                    ""MHExternalMakeId"": 0.0,
                    ""MHExternalModelId"": 0.0,
                    ""Floors"": [],
                    ""Units"": []
                }
            ],
            ""Details"": [],
            ""AddOns"": [],
            ""UserDetails"": [],
            ""DetachedGarages"": []
        }
        ";
    }
}
